services:
  node_app:
    image: node:lts-alpine3.19
    container_name: node_app_container
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src
      - /usr/src/homyz/node_modules
      - /usr/src/analysis/node_modules
      - /usr/src/analysis/myenv
    command: sh -c "apk add --no-cache python3 py3-pip curl dbus gnome-keyring && python3 -m venv myenv && source myenv/bin/activate && pip install --upgrade pip && pip install requests && cd ../homyz && npm install && echo \"DONE\" && tail -f /dev/null"
    working_dir: /usr/src/analysis
    ports:
      # malware
      - "3000:3000"
      - "4000:4000"
      # nodejs debugger :: https://nodejs.org/en/docs/inspector
      - "9229:9229"
